# Generated by Django 5.0.6 on 2024-06-26 03:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_sessiondata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_customer_id', models.CharField(help_text='Customer id returned from stripe after it saves subscription details', max_length=255)),
                ('user_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='authentication.userrole')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_subscription_id', models.CharField(help_text='Subscription id returned after subscription created event from stripe', max_length=255)),
                ('status', models.CharField(blank=True, help_text='Status of subscription like active, renewed etc', max_length=255, null=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='Date when subscription started', null=True)),
                ('ended_at', models.DateTimeField(blank=True, help_text='Date when subscription ended', null=True)),
                ('canceled_at', models.DateTimeField(blank=True, help_text='Date when subscription is cancelled', null=True)),
                ('expire_at_period_end', models.BooleanField(default=False, help_text='It indicates that subscription will expire at the end of the billing period after cancellation')),
                ('expire_at', models.DateTimeField(blank=True, help_text='It indicates at what date subscription will expire', null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='payments.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
