# Generated by Django 5.0.6 on 2024-07-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='base_calls_total',
            field=models.IntegerField(default=0, help_text='Number of base calls available during the subscription period'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='base_calls_used',
            field=models.IntegerField(default=0, help_text='Number of base calls reported during the subscription period'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='overage_calls_used',
            field=models.IntegerField(default=0, help_text='Number of overage calls reported during the subscription period'),
        ),
    ]
