# Generated by Django 5.0.6 on 2024-07-25 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_subscription_base_calls_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='base_calls_total',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='base_calls_used',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='overage_calls_used',
        ),
    ]
