# Generated by Django 5.0.6 on 2024-09-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_subscription_base_calls_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='first_discount_taken',
            field=models.BooleanField(default=False, help_text='Keep track if the first discount has already been applied or not'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='interval',
            field=models.CharField(default='month', help_text='Recurring interval of subscription like month or year', max_length=255),
        ),
    ]
