# Generated by Django 5.0.6 on 2024-06-22 17:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preferred_property_type', models.CharField(blank=True, max_length=255, null=True)),
                ('preferred_home_style', models.CharField(blank=True, max_length=255, null=True)),
                ('preferred_construction_material', models.CharField(blank=True, max_length=255, null=True)),
                ('industry', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('years_of_experience', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('home_built_per_year', models.CharField(blank=True, max_length=255, null=True)),
                ('license_number', models.PositiveIntegerField(blank=True, null=True)),
                ('bio', models.CharField(blank=True, null=True)),
                ('primary_service_area', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('province', models.CharField(blank=True, max_length=255, null=True)),
                ('zip_postal_code', models.PositiveIntegerField(blank=True, null=True)),
                ('website_url', models.URLField()),
                ('linkedin_profile', models.URLField()),
                ('instagram_profile', models.URLField()),
                ('twitter_profile', models.URLField()),
                ('facebook_page', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
