# Generated by Django 5.0.6 on 2024-06-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profilesettings_facebook_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilesettings',
            name='bio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
