# Generated by Django 5.0.6 on 2024-06-29 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profilesettings_bio'),
        ('users', '0003_report'),
    ]

    operations = [
    ]
