# Generated by Django 5.0.6 on 2024-06-30 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architectural_plans', '0005_alter_architecturalplan_units'),
        ('users', '0004_merge_0003_alter_profilesettings_bio_0003_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='architectural_plans',
            field=models.ManyToManyField(to='architectural_plans.architecturalplan'),
        ),
        migrations.AddField(
            model_name='report',
            name='comparable_sales',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='kpis',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='property',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='selected_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_in_reports', to='architectural_plans.architecturalplan'),
        ),
        migrations.AddField(
            model_name='report',
            name='zoning',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
