# Generated by Django 5.0.6 on 2024-07-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_report_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilesettings',
            name='is_multifactor_enabled',
            field=models.BooleanField(default=False, help_text='Stores users preference for turning multifactor on or off'),
        ),
    ]
