# Generated by Django 5.0.6 on 2024-07-08 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profilesettings_is_multifactor_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilesettings',
            name='is_multifactor_enabled',
        ),
    ]
