# Generated by Django 5.0.6 on 2024-09-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_profilesettings_is_multifactor_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilesettings',
            name='profile_picture',
            field=models.CharField(blank=True, help_text='Path of s3 uploaded profile picture', max_length=255, null=True),
        ),
    ]
