# Generated by Django 5.0.6 on 2024-10-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profilesettings_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='acquisition_cost',
            field=models.FloatField(default=0.0, help_text='Other acquisition cost listed in dashboard kpis'),
        ),
        migrations.AddField(
            model_name='report',
            name='other_cost',
            field=models.FloatField(default=0.0, help_text='Other development cost listed in dashboard kpis'),
        ),
    ]
