# Generated by Django 5.0.6 on 2024-06-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='address',
            field=models.CharField(blank=True, help_text='Address on which this chat gives real estate data', max_length=1000, null=True),
        ),
    ]
