# Generated by Django 5.0.6 on 2024-10-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_uncoveredaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='remaining_plans_query',
            field=models.JSONField(blank=True, help_text='Query to get remaining architectural plans', null=True),
        ),
    ]
