# Generated by Django 5.0.6 on 2024-06-29 07:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttomData',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(help_text='Address including street, city, state, country', max_length=500, unique=True)),
                ('comparable_sales', models.JSONField(blank=True, help_text='Comparable sales data received from attom', null=True)),
                ('property', models.JSONField(blank=True, help_text='Property data received from attom', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
