# Generated by Django 5.0.6 on 2024-07-16 05:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GISZoningCode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, help_text='Name of the city where the zoning area is located.', max_length=50, null=True)),
                ('state', models.CharField(blank=True, help_text='Name of the state where the zoning area is located.', max_length=50, null=True)),
                ('municode_zoning_code', models.CharField(blank=True, help_text='Zoning code mentioned in municode zoning rules.', max_length=50, null=True)),
                ('gis_zoning_code', models.CharField(blank=True, help_text='Zoning code mentioned in gis zoning rules.', max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
