# Generated by Django 5.0.6 on 2024-06-18 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_application', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Waitlist',
        ),
    ]
