# Generated by Django 4.1.13 on 2024-06-04 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionData',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(help_text='Django session ID', max_length=255)),
                ('property', models.JSONField(blank=True, null=True)),
                ('zoning', models.JSONField(blank=True, null=True)),
                ('user_choices', models.JSONField(blank=True, null=True)),
                ('query_property', models.JSONField(blank=True, null=True)),
                ('kpi', models.JSONField(blank=True, null=True)),
                ('architectural_plans', models.JSONField(blank=True, null=True)),
                ('selected_architectural_plan', models.JSONField(blank=True, null=True)),
                ('comparables', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
