# Generated by Django 5.0.6 on 2024-06-18 09:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MContactInfo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text='Enter the first name of the municipal contact.', max_length=255)),
                ('last_name', models.CharField(help_text='Enter the last name of the municipal contact.', max_length=255)),
                ('email', models.EmailField(help_text='Enter the email address of the municipal contact.', max_length=254, unique=True)),
                ('phone', models.CharField(help_text='Enter the phone number of the municipal contact, including area code.', max_length=20, unique=True)),
                ('municipality', models.CharField(help_text='Enter the name of the municipality.', max_length=255)),
                ('residential_permits_qty', models.PositiveIntegerField(blank=True, help_text='Enter the number of residential permits requests received in 2023 (optional).', null=True)),
                ('commercial_permits_qty', models.PositiveIntegerField(blank=True, help_text='Enter the number of commercial permits requests received in 2023 (optional).', null=True)),
                ('approving_requests', models.BooleanField(default=True, help_text='Indicate whether the contact is currently approving requests.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WaitlistUser',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text='Enter the first name of the individual joining the waitlist.', max_length=255)),
                ('last_name', models.CharField(help_text='Enter the last name of the individual joining the waitlist.', max_length=255)),
                ('email', models.EmailField(help_text='Enter the email address of the individual joining the waitlist.', max_length=254, unique=True)),
                ('occupation', models.CharField(help_text='Enter the occupation of the individual joining the waitlist.', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
