# Generated by Django 5.0.6 on 2024-09-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_crm', '0002_waitlistuser_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlistuser',
            name='email',
            field=models.EmailField(help_text='Enter the email address of the individual joining the waitlist.', max_length=254),
        ),
    ]
